name: github-action-libft

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    run:
        working-directory: ./test
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install siege -y
      - run: make MODE=debug
      - run: ./webserv ./conf/default.conf &
      - run: siege -c 2 -r 100 -b -t 10s http://127.0.0.1:8080
