name: github-action-libft

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    default:
      run:
        working-directory: ./test
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install siege -y
      - run: make MODE=debug -C ../
      - run: bash tester.sh
